version: '3'
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    restart: always
    ports:
    - 8080:80

  mysql:
    container_name: php-mysql
    image: mysql:5.7
    environment:
      MYSQL_USER: test
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: phpmyadmin
      MYSQL_PASSWORD: test
      MYSQL_ROOT_HOST: '%'
    ports:
    - 3306:3306